version: '3.8'

services:
  kafka-bridge-1:
    build: 
        context: .
        dockerfile: Dockerfile.txt
    container_name: erp-pms-sync-worker-1
    restart: always
    networks: 
        - pms-kafka-bridge-network
    
  kafka-bridge-2:
    build: 
        context: .
        dockerfile: Dockerfile.txt
    container_name: erp-pms-sync-worker-2
    restart: always
    networks: 
        - pms-kafka-bridge-network

networks:
  pms-kafka-bridge-network:
    driver: bridge  